; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32@^6.12.0
board = esp32-s3-devkitc-1
framework = arduino
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_LWIP_MAX_SOCKETS=16
	-Wl,--wrap=esp_panic_handler
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/mbedtls/mbedtls/include
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/mbedtls/port/include
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/mbedtls/esp-tls/esp_tls_crypto.h
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/esp_http_server/include
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/esp_https_server/include
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/lwip/include
build_unflags = -Wwrite-strings
board_build.filesystem = littlefs
build_type = debug
monitor_speed = 921600
monitor_encoding = UTF-8
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder, colorize
extra_scripts = post:archive_elf.py
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.0
	adafruit/Adafruit SH110X@^2.1.12
	cbm80amiga/RRE Font Library@^1.2.2
	lemmingdev/ESP32-BLE-Gamepad@^0.7.4
	fastled/FastLED@^3.9.14
	adafruit/Adafruit SSD1306@^2.5.16
